version: "3"
services:

  preprocess:
    build:
      context: .
      dockerfile: Dockerfile-preprocess
    volumes:
      - "${DATA_PATH}:/data/vbs/"

  data-layer:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "80:80"
    volumes:
      - ./server:/app  # Mount the local app directory to /app in the container
      - ./model:/app/model
      - "${DATA_PATH}:/data/vbs/"
    depends_on:
      preprocess:
        condition: service_completed_successfully
