# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /preprocess

# Add ffmpeg
RUN apt update && apt install -y ffmpeg

# Copy the requirements file into the container at /preprocess
COPY ./requirements.txt /preprocess/

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the preprocess code into the container
COPY ./scripts /preprocess/

#Copy the model into the container
COPY ./preprocess_model /preprocess/

# Start the preprocessing
CMD ["bash", "./preprocess.bash"]
