DATABASE_ROOT = '/data/vbs/'
DATABASE_IMAGES = '/data/vbs/images/'

BASE_MODEL = 'clip-laion'
BASE_DATASET = 'V3C'

BASE_K = 1000
BASE_ADD_FEATURES = 0
BASE_DOWNLOADING_SPEED_UP = 1
BASE_ROUNDING_SPEED_UP = 0
